### PR TITLE
WIP: Adding a Bigquery Target

### PR DESCRIPTION
**Pull request by jmriego**
## Problem

Adding a Bigquery Target
This is related to the issue #282

## Proposed changes

I already created a `pipelinewise-target-bigquery` which is now in its own repository and this PR is to have it available by default in PipelineWise. This means adding also a new fastsync target and updating the necessary documentation.

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [x] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [x] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [x] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by jmriego** [comment]
I still need to work on the tests and update the necessary documentation

**Comment by koszti** [comment]
I think you're on the right path regarding testing and seems like you've figured out many things. 

You need to start the dev project in docker:
```
cd dev-project
docker-compose up --build
```

Once the docker compose is ready open a new terminal and shell into the PPW docker container:
```
docker exec -it pipelinewise_dev bash
cd /opt/pipelinewise
```

To run unit tests: `pytest tests/units/ -vv`
To run end to end tests: `pytest tests/units/ -vv`

**Unit tests**

[test_fastsync_target_bigquery](https://github.com/jmriego/pipelinewise/blob/bigquery/tests/units/fastsync/commons/test_fastsync_target_bigquery.py): Tests in this file should run without real bigquery account and queries should be mocked. The logic how you're mocking bigquery looks fine, you need to collect the SQL strings and compare to expected SQLs. This requires some adjustments. 

[test_swap_tables](https://github.com/jmriego/pipelinewise/blob/1ea850917acdaa4ffea2900a50d82bb0ef3cb49c/tests/units/fastsync/commons/test_fastsync_target_bigquery.py#L216): This unit test somehow gives `google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application.`, which some further google methods have to be mocked.

**End to end tests**

BigQuery end-to-end tests need to be optional like the other non-open source components. This is because not everybody have BigQuery account and we should test only the open source components by default. To make BigQuery end-to-end tests optional:

1. Add new bigquery specific connection details as new vars (`TARGET_BIGQUERY_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS`) to [dev-project/.env](https://github.com/jmriego/pipelinewise/blob/1ea850917acdaa4ffea2900a50d82bb0ef3cb49c/dev-project/.env#L90)

2. Create a new optional bigquery specific env group in [tests/end_to_end/helpers/env.py](https://github.com/jmriego/pipelinewise/blob/1ea850917acdaa4ffea2900a50d82bb0ef3cb49c/tests/end_to_end/helpers/env.py#L150) and add the required config parameters (`TARGET_BIGQUERY_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS`)

3. Add `self.env['TARGET_SNOWFLAKE']['is_configured']` variable similar to  [here](https://github.com/jmriego/pipelinewise/blob/1ea850917acdaa4ffea2900a50d82bb0ef3cb49c/tests/end_to_end/helpers/env.py#L181)

At this point the bigquery specific end to end tests will run only if the details provided in the [dev-project/.env](https://github.com/jmriego/pipelinewise/blob/bigquery/dev-project/.env) or when it's available in system environment variables. In this way people and CI tools can decide when to run and when not to run BQ tests.

As you've found already e2e test cases should be in [test_target_bigquery.py](https://github.com/jmriego/pipelinewise/blob/bigquery/tests/end_to_end/test_target_bigquery.py). Just make sure to check if bigquery properties configured so e2e tests will be skipped if the credentials are not provided. But you've done it already [here](https://github.com/jmriego/pipelinewise/blob/1ea850917acdaa4ffea2900a50d82bb0ef3cb49c/tests/end_to_end/test_target_bigquery.py#L47)

I hope this helps

**Comment by jmriego** [comment]
Thanks a lot for your help! That was really useful to understand how it's all set up. I'll continue working on adding the tests

**Comment by jmriego** [comment]
Just to give you an update on this. I have already finished the unit tests and will continue working on the End to end tests

**Comment by jmriego** [comment]
Hi @koszti ,

I am stuck on the testing portion of it. For some reason I'm getting the error:
```
time=2020-07-28 11:04:49 logger_name=singer log_level=INFO message=METRIC: {"type": "counter", "metric": "record_count", "value": 1, "tags": {"database": "mysql_source_db", "table": "full"}}
time=2020-07-28 11:04:49 logger_name=singer log_level=INFO message=METRIC: {"type": "timer", "metric": "job_duration", "value": 0.006487607955932617, "tags": {"job_type": "sync_table", "database": "mysql_source_db", "table": "full", "status": "succeeded"}}
time=2020-07-28 11:04:49 logger_name=singer log_level=INFO message=METRIC: {"type": "timer", "metric": "job_duration", "value": 0.003932952880859375, "tags": {"job_type": "sync_binlog", "status": "failed"}}
time=2020-07-28 11:04:49 logger_name=tap_mysql log_level=CRITICAL message=Unable to replicate binlog stream because requested position (396153) for log file mysql-bin.000003 is greater than current position (264216).
Traceback (most recent call last):
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/bin/tap-mysql", line 8, in <module>
    sys.exit(main())
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 715, in main
    raise exc
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 712, in main
    main_impl()
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 705, in main_impl
    do_sync(mysql_conn, args.config, catalog, state)
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 657, in do_sync
    sync_binlog_streams(mysql_conn, binlog_catalog, config, state)
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 649, in sync_binlog_streams
    binlog.sync_binlog_stream(mysql_conn, config, binlog_catalog.streams, state)
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/binlog.py", line 429, in sync_binlog_stream
    verify_log_file_exists(mysql_conn, log_file, log_pos)
  File "/opt/pipelinewise/dev-project/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/binlog.py", line 90, in verify_log_file_exists
    raise Exception(f"Unable to replicate binlog stream because requested position ({log_pos}) "
Exception: Unable to replicate binlog stream because requested position (396153) for log file mysql-bin.000003 is greater than current position (264216).
```

That's during an end to end testing from mysql to bigquery using the tests you explained to me earlier. I don't see anything strange on the mysql_to_bigquery.py file and the state code looks the same as all other fastsync scripts. Any ideas where it could be failing? Thanks a lot!

**Comment by koszti** [comment]
Can you please confirm if the master branch of https://github.com/jmriego/pipelinewise/tree/bigquery is that gives this error?
I can try to reproduce and will come back with some answer

**Comment by jmriego** [comment]
Thanks a lot for your help! Yes, that's the branch I'm working on. You will also see some errors during the tests that compare source and target tables as bigquery does not support spaces in the names even when using quoting but you can ignore those. I'm working on that

File: pipelinewise/fastsync/postgres_to_bigquery.py [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+
+def tap_type_to_target_type(pg_type):
+    """Data type mapping from Postgres to Bigquery"""
+    return {
+        'char':'STRING',
+        'character':'STRING',
+        'varchar':'STRING',
+        'character varying':'STRING',
+        'text':'STRING',
+        'bit': 'BOOL',
```
Comment (DrudgeRajen) [inline pipelinewise/fastsync/postgres_to_bigquery.py:45]: Should we use some other data type instead of `bit` to `BOOL` because if column have bit data type will have data then it will fail to copy the data to bigquery tables?  We had same problem and used `STRING` instead.

Comment (jmriego) [reply pipelinewise/fastsync/postgres_to_bigquery.py:45]: I won't have much access to Internet for one week but I'll have a look at this after that. The rest of replications use BOOL in this case so I think it makes sense to do the same here. I'll check if this is working for both incremental and fastsync replication and fix accordingly

Comment (jmriego) [reply pipelinewise/fastsync/postgres_to_bigquery.py:45]: hi! I just did some testing and seems to be working as expected with both full and incremental load in a table with a `BIT` type column. Did you find any issue where that was not working? Could you give me more details so I can have a better look?

Comment (DrudgeRajen) [reply pipelinewise/fastsync/postgres_to_bigquery.py:45]: Does your column with `BIT` data type has value in it? The table which I was trying to sync in bigquery with BIT value failed with error `invalid boolean (011111...)`.

Comment (jmriego) [reply pipelinewise/fastsync/postgres_to_bigquery.py:45]: oh got it. I was testing it thinking that BIT was only of length one. I'll make the change.
`BIT VARYING` is being converted to number so I think it makes sense to make this one a number as well. Also, BigQuery has a few bit SQL functions that require a number so it would be compatible with that. I'll make the change.

https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/fastsync/postgres_to_snowflake.py#L50
@koszti does this affect the snowflake target as well?

Comment (koszti) [reply pipelinewise/fastsync/postgres_to_bigquery.py:45]: It makes sense but tap-postgres transforms bit to boolean in a weird way: https://github.com/transferwise/pipelinewise-tap-postgres/blob/c0eb14ebfe14b10ad208d10c5d1d7f1bf5b8be25/tap_postgres/sync_strategies/logical_replication.py#L242

fastsync postgres-to-bigquery should be in sync with the behaviour of tap-postgres, otherwise the initial sync and the following log-based replications will produce different column types :(

Can we use the existing bit-to-boolean transformation  from tap-postgres for now and later we can consider to change how tap-postgres dealing with bit types? what do you think?

Comment (jmriego) [reply pipelinewise/fastsync/postgres_to_bigquery.py:45]: sure, that makes sense. I'll check and make sure the bigquery code is doing exactly the same thing. thanks!

Comment (DrudgeRajen) [reply pipelinewise/fastsync/postgres_to_bigquery.py:45]: Yeah, a good idea to make it backward compatible.

**Comment by AlexStansfield** [comment]
@jmriego is this PR still under development?

We started using it and now want to create more pipelines but the PR hasn't really gotten closer to being merged. We're a little unsure about relying on this even more if it's dead and are looking at other options.

If it is still under development we are willing to contribute funds to its development if that helps.

**Comment by jmriego** [comment]
hi @AlexStansfield 

We have been using this target in production for a long time and haven't made too many changes since this PR. I will update this PR this week but I still have the problem that I don't know how to run the tests of MySQL with the binlog:
```
Exception: Unable to replicate binlog stream because requested position (396153) for log file mysql-bin.000003 is greater than current position (264216).
```

That's where I got stuck last time and if we can get help there we can unblock this and merge this target

**Comment by jmriego** [comment]
we actually might need to replicate from a mysql database with the binlog soon so that might help unblock this pull request

**Comment by AlexStansfield** [comment]
@jmriego heya, sorry to bug you again. Any chance this is any closer to being accepted into Pipelinewise?

At the moment we need to make a decision if we want to continue using this or move to something else.

Unfortunately we don't have any devs we can donate to the effort, but we are willing to provide funds if that might grease the wheels.

**Comment by jmriego** [comment]
hi @AlexStansfield ! I'll reply to you next week. I am not able to get this approved even because I can't get the docker tests passed, but to be honest many other docker tests fail so it's not really an issue with this BigQuery target. I can see they have changed the CI/CD testing two weeks ago so I'll give this another go

**Comment by jmriego** [comment]
I have good news about this. After rebasing the latest PipelineWise changes the unit testing completes successfully. I still need to work on the end_to_end project that includes some new test cases. This is no longer blocked. I'm working on that and expect to have something soon

**Comment by jmriego** [comment]
ok, I have all working now! Can we get someone to have a look and merge the target-bigquery changes?
https://github.com/transferwise/pipelinewise-target-bigquery/pull/12

If it makes sense I'm happy to help more with the maintenance of that repo

**Comment by koszti** [comment]
@jmriego thanks for the PR. I added a little comment to the transferwise/pipelinewise-target-bigquery#12 PR. Can you please have a look and then we can merge.

TBH we don't have to deep knowledge of bigquery so having someone like you to maintain the BigQuery components makes a lot sense.

**Comment by koszti** [comment]
pipelinewise-target-bigquery v1.1.1 is now available on PyPI at https://pypi.org/project/pipelinewise-target-bigquery/ 🙇

**Comment by jmriego** [comment]
hi! we have been running this new version in prod and all tests are passing. The last change I had to make was about the `certifi` library which seemed to have a conflict as it was installing 2020.05.30 which was not compatible with the Snowflake connector. I found an issue on their repo and seem to be working on that.

Please let me know of anything I should be adding or checking. Thanks!

File: pipelinewise/fastsync/commons/tap_mysql.py [hunk 2]
```diff
@@ -207,26 +222,32 @@ def get_table_columns(self, table_name):
                             WHEN data_type IN ('blob', 'tinyblob', 'mediumblob', 'longblob')
                                     THEN CONCAT('REPLACE(hex(`', column_name, '`)', ", '\n', ' ')")
                             WHEN data_type IN ('binary', 'varbinary')
-                                    THEN concat('REPLACE(hex(trim(trailing CHAR(0x00) from `',COLUMN_NAME,'`))', ", '\n', ' ')")
+                                    THEN concat('REPLACE(REPLACE(hex(trim(trailing CHAR(0x00) from `',COLUMN_NAME,'`))', ", '\n', ' '), '\r', '')")
```
Comment (koszti) [inline pipelinewise/fastsync/commons/tap_mysql.py:225]: why this is required?

File: pipelinewise/fastsync/commons/tap_mysql.py [hunk 3]
```diff
@@ -207,26 +222,32 @@ def get_table_columns(self, table_name):
...
                                     THEN concat('nullif(`', column_name, '`,STR_TO_DATE("0000-00-00 00:00:00", "%Y-%m-%d %T"))')
                             WHEN column_type IN ('tinyint(1)')
                                     THEN concat('CASE WHEN `' , column_name , '` is null THEN null WHEN `' , column_name , '` = 0 THEN 0 ELSE 1 END')
                             WHEN column_type IN ('geometry', 'point', 'linestring', 'polygon', 'multipoint', 'multilinestring', 'multipolygon', 'geometrycollection')
                                     THEN concat('ST_AsGeoJSON(', column_name, ')')
                             WHEN column_name = 'raw_data_hash'
-                                    THEN concat('REPLACE(hex(`', column_name, '`)', ", '\n', ' ')")
-                            ELSE concat('REPLACE(REPLACE(cast(`', column_name, '` AS char CHARACTER SET utf8)', ", '\n', ' '), '\0', '')")
+                                    THEN concat('REPLACE(REPLACE(hex(`', column_name, '`)', ", '\n', ' '), '\r', '')")
+                            WHEN data_type IN ('double', 'numeric', 'float', 'decimal', 'real')
```
Comment (koszti) [inline pipelinewise/fastsync/commons/tap_mysql.py:238]: same as above, can you please explain why the new conditions are required? Are they all backward compatible with supported targets?

**Comment by koszti** [comment]
thanks, it looks fine. You had to make changes in the fastsync SQL export which I think was required making the export compatible with BigQuery to import. Is there any impact on other targets, like snowflake or postgres or they're 100% backward compatibles?

File: pipelinewise/fastsync/commons/tap_mysql.py (hunk 2 above)
Comment (jmriego) [reply pipelinewise/fastsync/commons/tap_mysql.py:225]: the tap was removing newlines included in these fields but we had some data that we were extracting from a Windows system so it included `\r` and `\n`, not only `\n`
From what I see, this is a fix that would apply to more people, not really anything specific to BigQuery

File: pipelinewise/fastsync/commons/tap_mysql.py (hunk 3 above)
Comment (jmriego) [reply pipelinewise/fastsync/commons/tap_mysql.py:238]: this change was needed for BigQuery but might be useful to other targets. MySQL can have numbers bigger than what BigQuery accept or with more precision. What I'm doing here is rounding the numbers to something BigQuery would load. (For example, if it has too many decimals, BigQuery fails loading it. It doesn't round the number)

If you check the code just above this you'll see that if this function does not receive a `max_num` parameter, it will just select the field as is and won't round or do anything. So, if we want to load into any target with a similar restriction you just need to pass `max_num = 99999999.99999` or similar. Does that make sense?

**Comment by jmriego** [comment]
The changes I made were 100% compatible but I haven't been able to get the docker image running all test cases. I was having trouble running Snowflake test cases even in the base PipelineWise image. Do you have an automated test suite that could run all of them so we can be completely safe?

**Comment by koszti** [comment]
@jmriego, end to end test suite exists and integrated with snowflake but it's not running on forked repos. We need to have a branch in this repo to run e2e tests.

**Comment by jmriego** [comment]
thanks @koszti . I think I see all information that I need. Just to be sure, the target is make this work in 3.6, 3.7 and 3.8, right?
I might have to make some small fixes for that but probably nothing major

**Comment by koszti** [comment]
@jmriego yes, python 3.6 3.7 and 3.8 are the target versions. The linter, unit tests and end-to-end tests are currently failing. Do you use the docker based local test-env? If not then you can find some ideas below and might help pushing this PR through:


### To build local test env

Add `target-bigquery` to [entrypoint.sh](https://github.com/transferwise/pipelinewise/blob/0b9ae52070a4e06884d36b3d05a2370d520d62f9/dev-project/entrypoint.sh#L30) then build the containers:

```
cd dev-project
docker-compose up --build
```

Once it's completed ssh into the PPW by `docker exec -it pipelinewise_dev bash`


### Linter

Inside the PPW container:
```
cd /opt/pipelinewise
pylint pipelinewise
```
Currently rated to 9.86 but has to be 10.0. I think they're easy to fix formatting problems mostly.


### Unit tests
```
cd /opt/pipelinewise
pytest tests/units -vv
```
Currently failing mostly with `missing 1 required positional argument: 'target_quote'`

### End to end tests


```
cd /opt/pipelinewise
pytest tests/end_to_end/test_target_postgres.py -vv
pytest tests/end_to_end/test_target_bigquery.py -vv
```

Some issues when importing and running tests. Try to make it work for postgres and bigquery. Once they're green and if you don't have a snowflake account then l can check snowflake e2e tests.

**Comment by jmriego** [comment]
hi @koszti , sorry about that. I saw the error in actions and I commited a partial fix to the lint issues. The error in unit tests is because `pytest` seems to keep the loaded libraries in memory. When I change a module-level constant it's fine when running it outside of `pytest`. I'm doing some refactoring that I expect to have finished by tomorrow.
Also, about the linting I only did:
`pylint target_bigquery -d C,W,unexpected-keyword-arg,duplicate-code`

Since I saw the github actions I noticed I also need to check for:
`find pipelinewise tests -type f -name '*.py' | xargs unify --check-only` 
and `pylint pipelinewise tests` 

I think I will have all of this for tomorrow or Tuesday at the latest

**Comment by jmriego** [comment]
ok! I think so far everything's looking good. I added some unit tests that were still pending

File: tests/end_to_end/test_target_bigquery.py [hunk 4]
```diff
@@ -0,0 +1,308 @@
...
+    @pytest.mark.dependency(depends=['import_config'])
+    def test_resync_mariadb_to_bq_with_split_large_files(self, tap_mariadb_id=TAP_MARIADB_SPLIT_LARGE_FILES_ID):
+        """Resync tables from MariaDB to Bigquery using splitting large files option"""
+        assertions.assert_resync_tables_success(tap_mariadb_id, TARGET_ID, profiling=True)
+        assertions.assert_row_counts_equal(self.run_query_tap_mysql, self.run_query_target_bigquery)
+        assertions.assert_all_columns_exist(self.run_query_tap_mysql, self.run_query_target_bigquery,
+                                            mysql_to_bigquery.tap_type_to_target_type)
+
+    # pylint: disable=invalid-name
+    def test_resync_pg_to_bq_with_split_large_files(self, tap_postgres_id=TAP_POSTGRES_SPLIT_LARGE_FILES_ID):
```
Comment (koszti) [inline tests/end_to_end/test_target_bigquery.py:147]: This test is always running but should run only when it's configured. Can you please annotate this test with:
```
@pytest.mark.dependency(depends=['import_config'])
```

**Review by koszti — APPROVED** [review]

**Comment by koszti** [comment]
@jmriego it has been merged. Thank you for the lot of work it required 🙇 
I've just realised that a submodule remained in the main dir: ` Submodule pipelinewise-target-bigquery added at 363efe`

Can you please send a PR and remove it?

**Comment by koszti** [comment]
Also if you can send PR to add bigquery to the `README.md` and add a page to docs with bigquery target setup then it would be great. 

Supporting bigquery is definitely a milestone and would be nice to have proper documentation. 🙇

**Comment by jmriego** [comment]
That's great news! Happy to help and of course count on me for any mention of BigQuery issues that might arise

sorry about the submodule thing. That is the way we are running `pipelinewise` locally and I totally missed that. I just sent that merge request and will work on the documentation. Seems straightforward enough
